dsadsadsadas

diff --git a/.github/workflows/CloudfyBlue.yaml b/.github/workflows/CloudfyBlue.yaml
--- a/.github/workflows/CloudfyBlue.yaml
+++ b/.github/workflows/CloudfyBlue.yaml
@@ -296,55 +296,84 @@ jobs:
             ionic5/PDV/CloudfyBlue.apk
             ionic5/PDV/CloudfyBlue.aab
 
-  #Job que vai atualizar o git, sincronizar os fontes
   FinishJob:
     needs: [Android, Windows]
-    runs-on: windows-latest
-    if: success() && ${{ (inputs.windows) }}
+    runs-on: ubuntu-latest
+    if: success() && ${{ (inputs.android || inputs.windows) }}
     permissions:
       contents: write
     defaults:
       run:
-        working-directory: ./ionic5
+        working-directory: ./flutterrepo
+
     steps:
-      # Checkout do repositorio IONIC 5
+      # Checkout do repositório IONIC 5
       - uses: actions/checkout@v4
         with:
           repository: cloudfysystems/IONIC
           ref: Ionic5 # Branch padrão
           token: ${{ secrets.GH_TOKEN }}
           path: ionic5
-      # checkout do repositorio de versão
+
+      # checkout do repositório de versão
       - uses: actions/checkout@v4
         with:
           path: version-repo
+
       - name: Recuperando os commits entre produção e main
         id: log
-        shell: pwsh
+        continue-on-error: true
         run: |
           git config --global user.name "cloudfysystems"
-          git config --global user.email "cloudfysystem@gmail.com"        
-          git pull origin production                         
-
-          $commits = git log origin/production..origin/Ionic5 --pretty=format:"- %s (%an)<br>" --no-merges
-          echo "commit_messages<<EOF" >> $env:GITHUB_OUTPUT
-          echo "$commits" >> $env:GITHUB_OUTPUT
-          echo "EOF" >> $env:GITHUB_OUTPUT
+          git config --global user.email "cloudfysystem@gmail.com"
+          git config --global pull.rebase false
+          git pull origin production
+          commits=$(git log origin/production..origin/main --pretty=format:"- %s (%an)<br>" --no-merges)
+          {
+            echo "commit_messages<<EOF"
+            echo "$commits"
+            echo "EOF"
+          } >> $GITHUB_OUTPUT
           git checkout production
-
           git merge origin/Ionic5 --no-ff -m "gerando versao na falcatrua" --allow-unrelated-histories
-
           git push origin production
-
-        # Lendo a versão atual do repositório
-      - name: Ler versão atual e atualizar o numero da versao
+      - name: Ler versão atual e atualizar o version.json
         working-directory: version-repo
-        shell: powershell
         run: |
-          $json = Get-Content "version.json" | ConvertFrom-Json
-          $json.blue.patch++
-          $json | ConvertTo-Json -Depth 2 | Set-Content "version.json"
-           echo "VERSAO=$($json.blue.simple).$($json.blue.patch)" >> $env:GITHUB_ENV
+          json=$(cat version.json)
+          patch=$(echo "$json" | jq '.blue.patch + 1' | tr -d '"')          
+          simple=$(echo "$json" | jq -r '.blue.simple')
+
+          newjson=$(echo "$json" | jq ".blue.patch=$patch")
+          echo "$newjson" > version.json
+
+          VERSAO="${simple}.${patch}"
+          echo "Versão gerada: $VERSAO"
+
+          echo "VERSAO=$VERSAO" >> $GITHUB_ENV
+
+      - name: Ler url e tag html para email (Windows)
+        working-directory: version-repo
+        if: ${{ inputs.windows }}
+        run: |
+          URLWINDOWS="https://github.com/cloudfysystems/Version/releases/download/v${{env.VERSAO}}Blue/Cloudfyblue.Setup.${{env.VERSAO}}.exe"
+          echo "$URLWINDOWS"
+          TAGWINDOWS="<p><a href=\"$URLWINDOWS\">CloudfyBlueWindows.exe</a></p>"
+          echo "$TAGWINDOWS"
+          echo "TAGWINDOWS=$TAGWINDOWS" >> $GITHUB_ENV          
+          echo "URLWINDOWS=$URLWINDOWS" >> $GITHUB_ENV
+
+      - name: Ler url e tag html para email (Android)
+        if: ${{ inputs.android }}
+        working-directory: version-repo
+        run: |
+          URLANDROID="https://github.com/cloudfysystems/Version/releases/download/v${{env.VERSAO}}Blue/CloudfyBlue.apk"
+          echo "$URLANDROID"
+          TAGANDROID="<p><a href=\"$URLANDROID\">CloudfyBlueAndroid.apk</a></p>"
+          echo "$TAGANDROID"
+          echo "TAGANDROID=$TAGANDROID" >> $GITHUB_ENV          
+          echo "URLANDROID=$URLANDROID" >> $GITHUB_ENV
+
       - name: Download artifact windows
         if: ${{ inputs.windows }}
         uses: actions/download-artifact@v4
@@ -370,36 +399,72 @@ jobs:
           body: Release gerado automaticamente para windows.
         env:
           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+
+      # NOVO PASSO: chama API antes de enviar e-mail
+      # NOVO PASSO: chama API antes de enviar e-mail
+      - name: Chamar API de alteração de dados android
+        if: ${{ inputs.android }}
+        id: api_call_android
+        run: |
+          echo "Chamando API de validação..."
+          response=$(curl -s -o response.txt -w "%{http_code}" \
+            -X POST https://api.cloudfy.net.br/H02SF0107A \
+            -H "Content-Type: application/json" \
+            -d '{"JSON": true,"Parameters": {"Versao":"${{ env.VERSAO }}","PSW":"${{secrets.SENHA_API_ALTERAR_URL}}", "URL": "${{env.URLANDROID}}", "NR_ID": 2}}')
+
+          echo "Código HTTP: $response"
+          cat response.txt
+
+          if [ "$response" != "200" ]; then
+            echo "❌ Falha na chamada da API. Abortando workflow."
+            exit 1
+          fi
+      - name: Chamar API de alteração de dados windows
+        if: ${{ inputs.windows }}
+        id: api_call_windows
+        run: |
+          echo "Chamando API de validação..."
+          response=$(curl -s -o response.txt -w "%{http_code}" \
+            -X POST https://api.cloudfy.net.br/H02SF0107A \
+            -H "Content-Type: application/json" \
+            -d '{"JSON": true,"Parameters": {"Versao":"${{ env.VERSAO }}","PSW":"${{secrets.SENHA_API_ALTERAR_URL}}", "URL": "${{env.URLWINDOWS}}", "NR_ID": 1}}')
+
+          echo "Código HTTP: $response"
+          cat response.txt
+
+          if [ "$response" != "200" ]; then
+            echo "❌ Falha na chamada da API. Abortando workflow."
+            exit 1
+          fi
+
       - name: Envia e-mail com resumo
         uses: dawidd6/action-send-mail@v3
+        if: false
         with:
           server_address: mail.cloudfy.net.br
           server_port: 465
           username: ${{ secrets.EMAIL_USER }}
           password: ${{ secrets.EMAIL_PASS }}
-          subject: "Cloudfy blue - Gerado versão em produção "
+          subject: "Cloudfy blue - Gerado versão em produção"
           html_body: |
             <p><b>Olá time!</b></p>
 
             Foi gerada uma nova versão em produção do Cloudfy blue, na versão ${{env.VERSAO}}!<br><br>
+            Os arquivos foram atualizados na area de download da cloudfy (https://app.cloudfy.net.br/site/#/H02SF0107A)
 
             Commits incluídos:<br><br>
 
-            ${{ steps.log.outputs.commit_messages }}<br><br>
+            <b>${{ steps.log.outputs.commit_messages }}</b><br><br>            
 
             Segue o link para download:<br>
-            <p><a href="https://github.com/cloudfysystems/Version/releases/download/v${{env.VERSAO}}Blue/Cloudfyblue.Setup.${{env.VERSAO}}.exe">Cloudfyblue Setup ${{env.VERSAO}}.exe</a></p>
-            <p><a href="https://github.com/cloudfysystems/Version/releases/download/v${{env.VERSAO}}Blue/CloudfyBlue.apk">CloudfyBlue.apk</a></p>
-            <p><a href="https://github.com/cloudfysystems/Version/releases/download/v${{env.VERSAO}}Blue/CloudfyBlue.aab">CloudfyBlue.aab</a></p>
-
+            ${{env.TAGWINDOWS}}
+            ${{env.TAGANDROID}}
 
             <p><b>Menos foco, mais ansiedade!</b></p>
-
-          to: ${{vars.EMAIL}}
+          to: ${{ vars.EMAIL }}
           from: Cloudfy Versão <noreply@cloudfy.net.br>
           secure: true
 
-      # commit da atualização da versão
       - name: Commit das alterações
         uses: EndBug/add-and-commit@v9
         with:
