refeito patch

diff --git a/.github/workflows/SpeedyPosPatch.yml b/.github/workflows/SpeedyPosPatch.yml
--- a/.github/workflows/SpeedyPosPatch.yml
+++ b/.github/workflows/SpeedyPosPatch.yml
@@ -201,37 +201,41 @@ jobs:
           add: "versionWindows.json"
         env:
           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
-  Android-update:
+  android-prod:
     runs-on: ubuntu-latest
+    permissions:
+      contents: write
     defaults:
       run:
         working-directory: ./flutter/speed
 
     steps:
-      - name: Calculando a combinação dos booleans Android
-        id: compute
+      - name: Gerar Variáveis de Ambiente
         working-directory: .
+        id: compute
         run: |
-          ANDROID=${{ github.event.inputs.android-update }}
-          TEF=${{ github.event.inputs.android-tef-update }}
-          PAGSEGURO=${{ github.event.inputs.android-pagseguro }}
+          echo 'DeployName=prod' >> $GITHUB_ENV
+          echo 'DeployNameUpperCase=Prod' >> $GITHUB_ENV
+          echo 'UrlId=5' >> $GITHUB_ENV
+          VARIABLE=${{ github.event.inputs.android }}
 
           # Converte string para 0/1
-          if [ "$ANDROID" = "true" ]; then ANDROID_BOOL=1; else ANDROID_BOOL=0; fi
-          if [ "$TEF" = "true" ]; then TEF_BOOL=1; else TEF_BOOL=0; fi
-          if [ "$PAGSEGURO" = "true" ]; then PAGSEGURO_BOOL=1; else PAGSEGURO_BOOL=0; fi
+          if [ "$VARIABLE" = "true" ]; then VARIABLE_BOOL=1; else VARIABLE_BOOL=0; fi          
+
 
           # OR lógico
-          if [ $((ANDROID_BOOL | TEF_BOOL | PAGSEGURO_BOOL)) -eq 1 ]; then
-            COMBINED=true
+          if [ $((VARIABLE_BOOL)) -eq 1 ]; then
+            EXECUTE=true
           else
-            COMBINED=false
+            EXECUTE=false
           fi
 
-          echo "combined=$COMBINED" >> $GITHUB_OUTPUT
+          echo "Valor do execute: $EXECUTE"
+
+          echo "execute=$EXECUTE" >> $GITHUB_OUTPUT
       # Clonar o repositório principal do Flutter
       - uses: actions/checkout@v4
-        if: ${{ steps.compute.outputs.combined == 'true' }}
+        if: ${{ (steps.compute.outputs.execute == 'true') }}
         with:
           repository: cloudfysystems/FLUTTER
           ref: main
@@ -240,62 +244,42 @@ jobs:
 
       # Clonar o repositório de versão
       - uses: actions/checkout@v4
-        if: ${{ steps.compute.outputs.combined == 'true' }}
+        if: ${{ (steps.compute.outputs.execute == 'true') }}
         with:
           path: version-repo
 
       # Ler e atualizar a versão
-      - name: Ler versão atual (prod)
-        if: ${{ inputs.android-update }}
+      - name: Ler versão atual
+        if: ${{ (steps.compute.outputs.execute == 'true') }}
         working-directory: version-repo
         shell: bash
         run: |
-          VERSION_FILE="version.json"
-          BUILD=$(jq '.speedyAndroid.build' $VERSION_FILE)
-          VERSION=$(jq '.speedyAndroid.version' $VERSION_FILE)
-          SIMPLE=$(jq -r '.speedyAndroid.simple' $VERSION_FILE)
-          PATCH=$(jq -r '.speedyAndroid.patch += 1 | .speedyAndroid.patch' $VERSION_FILE)
+          VERSION_FILE="version${{env.DeployNameUpperCase}}.json"
+
+          # Atualiza o JSON corretamente
+          jq '.speedy.patch += 1' "$VERSION_FILE" > tmp.json
+
+          mv tmp.json "$VERSION_FILE"
+
+          # Pega os valores após a atualização
+          BUILD=$(jq -r '.speedy.build' "$VERSION_FILE")
+          VERSION=$(jq -r '.speedy.version' "$VERSION_FILE")
+          SIMPLE=$(jq -r '.speedy.simple' "$VERSION_FILE")
+          PATCH=$(jq -r '.speedy.patch' "$VERSION_FILE")
+
           echo "Versao Build: $BUILD"
           echo "Versao Version: $VERSION"
-          echo "Versao Gerada: $SIMPLE.$VERSION.0"
-          echo "VERSAO=$SIMPLE.$VERSION.$PATCH+$BUILD" >> $GITHUB_ENV
-          echo "VERSAOOLD=$SIMPLE.$VERSION.0+$BUILD" >> $GITHUB_ENV
+          echo "Versao Gerada: $SIMPLE.$VERSION.$PATCH"
 
-      - name: Ler versão atual (tef)
-        if: ${{ inputs.android-tef-update }}
-        working-directory: version-repo
-        shell: bash
-        run: |
-          VERSION_FILE="version.json"
-          BUILD=$(jq '.speedyAndroidTef.build' $VERSION_FILE)
-          VERSION=$(jq '.speedyAndroidTef.version' $VERSION_FILE)
-          SIMPLE=$(jq -r '.speedyAndroidTef.simple' $VERSION_FILE)
-          PATCH=$(jq -r '.speedyAndroidTef.patch += 1 | .speedyAndroidTef.patch' $VERSION_FILE)
-          echo "Versao tef Build: $BUILD"
-          echo "Versao tef Version: $VERSION"
-          echo "Versao tef Gerada: $SIMPLE.$VERSION.0"
-          echo "VERSAOTEF=$SIMPLE.$VERSION.$PATCH+$BUILD" >> $GITHUB_ENV
-          echo "VERSAOTEFOLD=$SIMPLE.$VERSION.0-tef+$BUILD" >> $GITHUB_ENV
+          echo "VERSAOOLD=$SIMPLE.$VERSION.0+$BUILD" >> $GITHUB_ENV          
+          echo "VERSAO=$SIMPLE.$VERSION.$PATCH" >> $GITHUB_ENV
 
-      - name: Ler versão atual (pagseguro)
-        if: ${{ inputs.android-pagseguro }}
-        working-directory: version-repo
-        shell: bash
-        run: |
-          VERSION_FILE="version.json"
-          BUILD=$(jq '.speedyAndroidPagSeguro.build' $VERSION_FILE)
-          VERSION=$(jq '.speedyAndroidPagSeguro.version' $VERSION_FILE)
-          SIMPLE=$(jq -r '.speedyAndroidPagSeguro.simple' $VERSION_FILE)
-          PATCH=$(jq -r '.speedyAndroidPagSeguro.patch += 1 | .speedyAndroidPagSeguro.patch' $VERSION_FILE)
-          echo "Versao tef Build: $BUILD"
-          echo "Versao tef Version: $VERSION"
-          echo "Versao tef Gerada: $SIMPLE.$VERSION.0"
-          echo "VERSAOPAGSEGURO=$SIMPLE.$VERSION.$PATCH+$BUILD" >> $GITHUB_ENV
-          echo "VERSAOPAGSEGUROOLD=$SIMPLE.$VERSION.0-pagseguro+$BUILD" >> $GITHUB_ENV
+          echo "Novo JSON:"
+          cat "$VERSION_FILE"
 
       # Criar o arquivo env/prod.json
       - name: Gerar env/prod.json
-        if: ${{ steps.compute.outputs.combined == 'true' }}
+        if: ${{ (steps.compute.outputs.execute == 'true') }}
         run: |
           mkdir -p ./env
           echo '${{ secrets.ENV_PROD }}' > ./env/prod.json
@@ -303,7 +287,7 @@ jobs:
 
       # Criar arquivo .jks a partir de base64
       - name: Criar arquivo .jks
-        if: ${{ steps.compute.outputs.combined == 'true' }}
+        if: ${{ (steps.compute.outputs.execute == 'true') }}
         shell: bash
         run: |
           mkdir -p certificado
@@ -311,14 +295,14 @@ jobs:
 
       # Setup Shorebird
       - name: 🐦 Setup Shorebird
-        if: ${{ steps.compute.outputs.combined == 'true' }}
+        if: ${{ (steps.compute.outputs.execute == 'true') }}
         uses: shorebirdtech/setup-shorebird@v1
         with:
           cache: true
 
       # Criar arquivo key.properties
       - name: Criar arquivo key.properties
-        if: ${{ steps.compute.outputs.combined == 'true' }}
+        if: ${{ (steps.compute.outputs.execute == 'true') }}
         shell: bash
         run: |
           echo "storePassword=${{ secrets.SENHA_KEYSTORE }}" > android/key.properties
@@ -328,15 +312,15 @@ jobs:
 
       # Set Up Java (usando Oracle JDK 17)
       - name: Set Up Java
-        if: ${{ steps.compute.outputs.combined == 'true' }}
+        if: ${{ (steps.compute.outputs.execute == 'true') }}
         uses: actions/setup-java@v3
         with:
           distribution: "oracle"
           java-version: "17"
 
-        # Atualizar versão no arquivo Dart
-      - name: Atualiza versão no arquivo Dart (prod)
-        if: ${{ inputs.android-update }}
+      # Atualizar versão no arquivo Dart
+      - name: Atualiza versão no arquivo Dart e pubspec.yaml
+        if: ${{ (steps.compute.outputs.execute == 'true') }}
         shell: bash
         run: |
           FILE="lib/Environment/Version.dart"
@@ -347,54 +331,71 @@ jobs:
       - name: Gerar Patch Android (Prod)
         uses: shorebirdtech/shorebird-patch@v1
         id: shorebird-patch
-        if: ${{ inputs.android-update }}
+        if: ${{ (steps.compute.outputs.execute == 'true') }}
         with:
           platform: android
           args: --allow-asset-diffs --flavor prod -- --dart-define-from-file=env/prod.json --dart-define=FLAVOR=prod
           release-version: ${{env.VERSAOOLD}}
           working-directory: ./flutter/speed
 
-      # Atualizar versão no arquivo Dart
-      - name: Atualiza versão no arquivo Dart (tef)
-        if: ${{ inputs.android-tef-update }}
-        shell: bash
+      - name: Chamar API de alteração de dados android
+        if: ${{ (steps.compute.outputs.execute == 'true') }}
         run: |
-          FILE="lib/Environment/Version.dart"
-          NOVA_VERSAO="${{ env.VERSAOTEF }}"
-          sed -i "s/const String Version = \".*\"/const String Version = \"$NOVA_VERSAO\"/" $FILE
-          cat lib/Environment/Version.dart
+          JSON_DATA=$(cat <<EOF
+          {
+            "JSON": true,
+            "Parameters": {
+              "Versao": "${{ env.VERSAO }}",
+              "PSW": "${{ secrets.SENHA_API_ALTERAR_URL }}",              
+              "NR_ID": ${{ env.UrlId }}
+            }
+          }
+          EOF
+          )
 
-      - name: Gerar Patch Android (tef)
-        uses: shorebirdtech/shorebird-patch@v1
-        id: shorebird-patch-tef
-        if: ${{ inputs.android-tef-update }}
-        with:
-          platform: android
-          args: --allow-asset-diffs --flavor tef -- --dart-define-from-file=env/prod.json --dart-define=FLAVOR=tef
-          release-version: ${{env.VERSAOTEFOLD}}
-          working-directory: ./flutter/speed
+          echo $JSON_DATA
 
-      # Atualizar versão no arquivo Dart
-      - name: Atualiza versão no arquivo Dart (pagseguro)
-        if: ${{ inputs.android-pagseguro }}
-        shell: bash
+          response=$(curl -s -o response.txt -w "%{http_code}" \
+            -X POST https://api.cloudfy.net.br/H02SF0107A \
+            -H "Content-Type: application/json" \
+            -d "$JSON_DATA")
+
+          echo "Código HTTP: $response"
+          cat response.txt
+
+          if [ "$response" != "200" ]; then
+            echo "❌ Falha na chamada da API. Abortando workflow."
+            exit 1
+          fi
+
+      - name: Atualizar branch com merge (se necessário)
+        if: ${{ (steps.compute.outputs.execute == 'true') }}
+        working-directory: version-repo
         run: |
-          FILE="lib/Environment/Version.dart"
-          NOVA_VERSAO="${{ env.VERSAOPAGSEGURO }}"
-          sed -i "s/const String Version = \".*\"/const String Version = \"$NOVA_VERSAO\"/" $FILE
-          cat lib/Environment/Version.dart
+          git config user.name "cloudfysystems"
+          git config user.email "cloudfysystems@gmail.com"
 
-      - name: Gerar Patch Android (pagseguro)
-        uses: shorebirdtech/shorebird-patch@v1
-        id: shorebird-patch-pagseguro
-        if: ${{ inputs.android-pagseguro }}
+          # Garante que estamos na branch correta
+          git branch --show-current
+
+          # Tenta fazer pull e merge automático
+          git pull origin HEAD --no-rebase || true
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+
+      - name: Commit das alterações
+        uses: EndBug/add-and-commit@v9
+        if: ${{ (steps.compute.outputs.execute == 'true') }}
         with:
-          platform: android
-          args: --allow-asset-diffs --flavor pagseguro -- --dart-define-from-file=env/prod.json --dart-define=FLAVOR=pagseguro
-          release-version: ${{env.VERSAOPAGSEGUROOLD}}
-          working-directory: ./flutter/speed
+          author_name: cloudfysystems
+          author_email: cloudfysystems@gmail.com
+          message: "alterada versão do build ${{env.DeployNameUpperCase}}"
+          cwd: ./version-repo
+          add: "version${{env.DeployNameUpperCase}}.json"
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
   FinishJob-update:
-    needs: [Android-update, Windows-update]
+    needs: [android-prod, Windows-update]
     runs-on: ubuntu-latest
     permissions:
       contents: write
