dsadsadsadsa

diff --git a/.github/workflows/SpeedyPosGerarVersao.yml b/.github/workflows/SpeedyPosGerarVersao.yml
--- a/.github/workflows/SpeedyPosGerarVersao.yml
+++ b/.github/workflows/SpeedyPosGerarVersao.yml
@@ -15,6 +15,10 @@ on:
         description: "Gerar versão Android?"
         default: false
         type: boolean
+      android-tef:
+        description: "Gerar versão Android(TEF)?"
+        default: false
+        type: boolean
       windows-update:
         description: "Atualizar versão Windows (Patch)?"
         default: true
@@ -22,6 +26,10 @@ on:
       android-update:
         description: "Atualizar versão Android (Patch)?"
         default: true
+        type: boolean
+      android-tef-update:
+        description: "Atualizar versão Android(TEF)?"
+        default: false
         type: boolean
 env:
   VERSION: ${{vars.VERSAO}}
@@ -245,9 +253,27 @@ jobs:
         working-directory: ./flutter/speed
 
     steps:
+      - name: Calculando a combinação dos booleans Android
+        id: compute
+        run: |
+          ANDROID=${{ github.event.inputs.android }}
+          TEF=${{ github.event.inputs.android-tef }}
+
+          # Converte string para 0/1
+          if [ "$ANDROID" = "true" ]; then ANDROID_BOOL=1; else ANDROID_BOOL=0; fi
+          if [ "$TEF" = "true" ]; then TEF_BOOL=1; else TEF_BOOL=0; fi
+
+          # OR lógico
+          if [ $((ANDROID_BOOL | TEF_BOOL)) -eq 1 ]; then
+            COMBINED=true
+          else
+            COMBINED=false
+          fi
+
+          echo "combined=$COMBINED" >> $GITHUB_OUTPUT
       # Clonar o repositório principal do Flutter
       - uses: actions/checkout@v4
-        if: ${{ inputs.android }}
+        if: ${{ steps.compute.outputs.combined }}
         with:
           repository: cloudfysystems/FLUTTER
           ref: main
@@ -256,13 +282,13 @@ jobs:
 
       # Clonar o repositório de versão
       - uses: actions/checkout@v4
-        if: ${{ inputs.android }}
+        if: ${{ steps.compute.outputs.combined}}
         with:
           path: version-repo
 
       # Ler e atualizar a versão
       - name: Ler versão atual
-        if: ${{ inputs.android }}
+        if: ${{ steps.compute.outputs.combined }}
         working-directory: version-repo
         shell: bash
         run: |
@@ -278,7 +304,7 @@ jobs:
 
       # Criar o arquivo env/prod.json
       - name: Gerar env/prod.json
-        if: ${{ inputs.android }}
+        if: ${{ steps.compute.outputs.combined }}
         run: |
           mkdir -p ./env
           echo '${{ secrets.ENV_PROD }}' > ./env/prod.json
@@ -286,7 +312,7 @@ jobs:
 
       # Atualizar versão no arquivo Dart
       - name: Atualiza versão no arquivo Dart
-        if: ${{ inputs.android }}
+        if: ${{ steps.compute.outputs.combined }}
         shell: bash
         run: |
           FILE="lib/Environment/Version.dart"
@@ -296,7 +322,7 @@ jobs:
 
       # Atualizar versão no pubspec.yaml
       - name: Atualizar versão no pubspec.yaml
-        if: ${{ inputs.android }}
+        if: ${{ steps.compute.outputs.combined }}
         shell: bash
         run: |
           sed -i "s/^version:.*/version: $VERSAO/" pubspec.yaml
@@ -304,34 +330,22 @@ jobs:
 
       # Criar arquivo .jks a partir de base64
       - name: Criar arquivo .jks
-        if: ${{ inputs.android }}
+        if: ${{ steps.compute.outputs.combined }}
         shell: bash
         run: |
           mkdir -p certificado
-          echo "${{ secrets.KEYSTORE }}" | base64 -d > certificado/certificado-keystore.jks
-
-      # Resolver problema incremental do Gradle
-      #- name: Resolver problema incremental do gradle
-      #  if: ${{ inputs.android }}
-      #  shell: bash
-      #  run: |
-      #    echo "kotlin.incremental=false" >> ./android/gradle.properties
-
-      # Habilitar longpath do git (não necessário no Ubuntu, mas mantido por compatibilidade)
-      #- name: Ajustar git longpath
-      #  if: ${{ inputs.android }}
-      #  run: git config --global core.longpaths true
+          echo "${{ steps.compute.outputs.combined }}" | base64 -d > certificado/certificado-keystore.jks
 
       # Setup Shorebird
       - name: 🐦 Setup Shorebird
-        if: ${{ inputs.android }}
+        if: ${{ steps.compute.outputs.combined }}
         uses: shorebirdtech/setup-shorebird@v1
         with:
           cache: true
 
       # Criar arquivo key.properties
       - name: Criar arquivo key.properties
-        if: ${{ inputs.android }}
+        if: ${{ steps.compute.outputs.combined }}
         shell: bash
         run: |
           echo "storePassword=${{ secrets.SENHA_KEYSTORE }}" > android/key.properties
@@ -341,56 +355,50 @@ jobs:
 
       # Set Up Java (usando Oracle JDK 17)
       - name: Set Up Java
-        if: ${{ inputs.android }}
+        if: ${{ steps.compute.outputs.combined }}
         uses: actions/setup-java@v3
         with:
           distribution: "oracle"
           java-version: "17"
 
       # Executar build do Shorebird
-      - name: 🚀 Shorebird Release
+      - name: 🚀 Shorebird Release (Prod)
         if: ${{ inputs.android }}
         id: shorebird-release
         uses: shorebirdtech/shorebird-release@v1
         with:
-          args: --flavor=prod --artifact apk -- --dart-define-from-file=env/prod.json
+          args: --flavor=prod --artifact apk -- --dart-define-from-file=env/prod.json --dart-define=FLAVOR=prod
           platform: android
           flutter-version: 3.32.8
           working-directory: ./flutter/speed
 
-      # Verificar se o bundle foi gerado
-      - name: Verificar bundle gerado
-        if: ${{ inputs.android }}
-        shell: bash
-        run: |
-          if [ ! -f "build/app/outputs/bundle/prodRelease/app-prod-release.aab" ]; then
-            echo "❌ Arquivo .aab não encontrado"
-            exit 1
-          else
-            echo "✅ Bundle gerado com sucesso"
-          fi
-
-      # Verificar se o APK foi gerado
-      - name: Verificar APK gerado
-        if: ${{ inputs.android }}
-        shell: bash
-        run: |
-          if [ ! -f "build/app/outputs/apk/prod/release/app-prod-release.apk" ]; then
-            echo "❌ APK não encontrado"
-            exit 1
-          else
-            echo "✅ APK gerado com sucesso"
-          fi
+      - name: 🚀 Shorebird Release (Tef)
+        if: ${{ inputs.android-tef }}
+        id: shorebird-release-tef
+        uses: shorebirdtech/shorebird-release@v1
+        with:
+          args: --flavor=tef --artifact apk -- --dart-define-from-file=env/prod.json --dart-define=FLAVOR=tef
+          platform: android
+          flutter-version: 3.32.8
+          working-directory: ./flutter/speed
 
       # Upload dos artefatos
-      - name: Upload da apk e do bundle
-        if: ${{ inputs.android }}
+      - name: Upload da apk e do bundle (Prod)
+        if: ${{ inputs.android}}
         uses: actions/upload-artifact@v4
         with:
           name: ApkBundleSpeedyAndroid
           path: |
             flutter/speed/build/app/outputs/apk/prod/release/app-prod-release.apk
             flutter/speed/build/app/outputs/bundle/prodRelease/app-prod-release.aab
+      - name: Upload da apk e do bundle (tef)
+        if: ${{inputs.android-tef}}
+        uses: actions/upload-artifact@v4
+        with:
+          name: ApkBundleSpeedyAndroidTef
+          path: |
+            flutter/speed/build/app/outputs/apk/tef/release/app-tef-release.apk
+            flutter/speed/build/app/outputs/bundle/tefRelease/app-tef-release.aab
   Android-update:
     runs-on: ubuntu-latest
     defaults:
@@ -511,8 +519,26 @@ jobs:
         working-directory: ./flutterrepo
 
     steps:
+      - name: Calculando a combinação dos booleans Android
+        id: compute
+        run: |
+          ANDROID=${{ github.event.inputs.android }}
+          TEF=${{ github.event.inputs.android-tef }}
+
+          # Converte string para 0/1
+          if [ "$ANDROID" = "true" ]; then ANDROID_BOOL=1; else ANDROID_BOOL=0; fi
+          if [ "$TEF" = "true" ]; then TEF_BOOL=1; else TEF_BOOL=0; fi
+
+          # OR lógico
+          if [ $((ANDROID_BOOL | TEF_BOOL)) -eq 1 ]; then
+            COMBINED=true
+          else
+            COMBINED=false
+          fi
+
+          echo "androidCombined=$COMBINED" >> $GITHUB_OUTPUT
       - uses: actions/checkout@v4
-        if: ${{ (inputs.android || inputs.windows) }}
+        if: ${{ (steps.compute.outputs.androidCombined || inputs.windows) }}
         with:
           repository: cloudfysystems/FLUTTER
           fetch-depth: 0
@@ -521,13 +547,13 @@ jobs:
           path: flutterrepo
 
       - uses: actions/checkout@v4
-        if: ${{ (inputs.android || inputs.windows) }}
+        if: ${{ (steps.compute.outputs.androidCombined || inputs.windows) }}
         with:
           path: version-repo
 
       - name: Recuperando os commits entre produção e main
         id: log
-        if: ${{ (inputs.android || inputs.windows) }}
+        if: ${{ (steps.compute.outputs.androidCombined || inputs.windows) }}
         continue-on-error: true
         run: |
           git config --global user.name "cloudfysystems"
@@ -592,8 +618,15 @@ jobs:
           echo "TAGANDROID=$TAGANDROID" >> $GITHUB_ENV          
           echo "URLANDROID=$URLANDROID" >> $GITHUB_ENV
 
+          URLANDROIDTEF="https://github.com/cloudfysystems/Version/releases/download/v$VERSAO/CloudfySpeedyPosTef.apk"
+          echo "$URLANDROIDTEF"
+          TAGANDROIDTEF="<p><a href=\"$URLANDROIDTEF\">CloudfySpeedyPosTef.apk</a></p>"
+          echo "$TAGANDROIDTEF"
+          echo "TAGANDROIDTEF=$TAGANDROIDTEF" >> $GITHUB_ENV          
+          echo "URLANDROIDTEF=$URLANDROIDTEF" >> $GITHUB_ENV
+
       - name: Gravar arquivo de versionamento
-        if: ${{ (inputs.android || inputs.windows) }}
+        if: ${{ (steps.compute.outputs.androidCombined || inputs.windows) }}
         working-directory: version-repo
         run: |
           if [ -f "version_android.json" ]; then
@@ -622,14 +655,20 @@ jobs:
         with:
           name: ApkBundleSpeedyAndroid
           path: ./downloadedApk
+      - name: Download artifact Android
+        if: ${{ inputs.android-tef }}
+        uses: actions/download-artifact@v4
+        with:
+          name: ApkBundleSpeedyAndroidTef
+          path: ./downloadedApk
       - name: Listar o working directory
-        if: ${{ (inputs.android || inputs.windows) }}
+        if: ${{ (steps.compute.outputs.androidCombined || inputs.windows) }}
         working-directory: .
         run: |
           ls -la
 
       - name: Renomear arquivos Android
-        if: ${{ inputs.android }}
+        if: ${{ steps.compute.outputs.androidCombined }}
         working-directory: .
         run: |
           echo "Renomeando APK e AAB..."
@@ -647,8 +686,23 @@ jobs:
             echo "⚠️ AAB não encontrado!"
           fi
 
+          echo "Renomeando APK e AAB (TEF)..."
+          if [ -f "downloadedApk/apk/tef/release/app-tef-release.apk" ]; then
+            mv downloadedApk/apk/tef/release/app-tef-release.apk downloadedApk/apk/tef/release/CloudfySpeedyPosTef.apk
+            echo "APK renomeado para CloudfySpeedyPosTef.apk"
+          else
+            echo "⚠️ APK não encontrado!"
+          fi
+
+          if [ -f "downloadedApk/bundle/tefRelease/app-tef-release.aab" ]; then
+            mv downloadedApk/bundle/tefRelease/app-tef-release.aab downloadedApk/bundle/tefRelease/CloudfySpeedyPosTef.aab
+            echo "AAB renomeado para CloudfySpeedyPosTef.aab"
+          else
+            echo "⚠️ AAB não encontrado!"
+          fi
+
       - name: Criando o release
-        if: ${{ (inputs.android || inputs.windows) }}
+        if: ${{ (steps.compute.outputs.androidCombined || inputs.windows) }}
         uses: softprops/action-gh-release@v1
         with:
           tag_name: v${{ env.VERSAO }}
@@ -657,12 +711,12 @@ jobs:
             downloaded/CloudfySpeedyPos.exe
             downloadedApk/apk/prod/release/CloudfySpeedyPos.apk
             downloadedApk/bundle/prodRelease/CloudfySpeedyPos.aab
+            downloadedApk/apk/tef/release/CloudfySpeedyPosTef.apk
+            downloadedApk/bundle/tefRelease/CloudfySpeedyPosTef.aab
           body: Release gerado automaticamente.
         env:
           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
 
-      # NOVO PASSO: chama API antes de enviar e-mail
-      # NOVO PASSO: chama API antes de enviar e-mail
       - name: Chamar API de alteração de dados android
         if: ${{ inputs.android }}
         id: api_call_android
@@ -672,6 +726,23 @@ jobs:
             -X POST https://api.cloudfy.net.br/H02SF0107A \
             -H "Content-Type: application/json" \
             -d '{"JSON": true,"Parameters": {"Versao":"${{ env.VERSAO }}","PSW":"${{secrets.SENHA_API_ALTERAR_URL}}", "URL": "${{env.URLANDROID}}", "NR_ID": 5}}')
+
+          echo "Código HTTP: $response"
+          cat response.txt
+
+          if [ "$response" != "200" ]; then
+            echo "❌ Falha na chamada da API. Abortando workflow."
+            exit 1
+          fi
+      - name: Chamar API de alteração de dados android(tef)
+        if: ${{ inputs.android-android-tef }}
+        id: api_call_android-tef
+        run: |
+          echo "Chamando API de validação..."
+          response=$(curl -s -o response.txt -w "%{http_code}" \
+            -X POST https://api.cloudfy.net.br/H02SF0107A \
+            -H "Content-Type: application/json" \
+            -d '{"JSON": true,"Parameters": {"Versao":"${{ env.VERSAO }}","PSW":"${{secrets.SENHA_API_ALTERAR_URL}}", "URL": "${{env.URLANDROIDTEF}}", "NR_ID": 11}}')
 
           echo "Código HTTP: $response"
           cat response.txt
@@ -700,7 +771,7 @@ jobs:
 
       - name: Envia e-mail com resumo
         uses: dawidd6/action-send-mail@v3
-        if: ${{ (inputs.android || inputs.windows) }}
+        if: ${{ (steps.compute.outputs.androidCombined || inputs.windows) }}
         with:
           server_address: mail.cloudfy.net.br
           server_port: 465
@@ -719,6 +790,7 @@ jobs:
             Segue o link para download:<br>
             ${{env.TAGWINDOWS}}
             ${{env.TAGANDROID}}
+            ${{env.TAGANDROIDTEF}}
 
             <p><b>Menos foco, mais ansiedade!</b></p>
           to: ${{ vars.EMAIL }}
@@ -727,7 +799,7 @@ jobs:
 
       - name: Commit das alterações
         uses: EndBug/add-and-commit@v9
-        if: ${{ (inputs.android || inputs.windows) }}
+        if: ${{ (steps.compute.outputs.androidCombined || inputs.windows) }}
         with:
           author_name: cloudfysystems
           author_email: cloudfysystems@gmail.com
