dsadsada

diff --git a/.github/workflows/SpeedyPosGerarVersao.yml b/.github/workflows/SpeedyPosGerarVersao.yml
--- a/.github/workflows/SpeedyPosGerarVersao.yml
+++ b/.github/workflows/SpeedyPosGerarVersao.yml
@@ -51,6 +51,10 @@ on:
         description: "Gerar versão iOS?"
         default: false
         type: boolean
+      macos:
+        description: "Gerar versão MacOS?"
+        default: false
+        type: boolean
       windows-profile:
         description: "Gerar versão Windows (Profile/Debug?"
         default: false
@@ -3017,6 +3021,206 @@ jobs:
       - name: Upload IPA to App Store Connect
         if: ${{ inputs.ios}}
         run: xcrun altool --upload-app --type ios -f ./build/ios/ipa/CloudfySpeedyPos.ipa --apiKey ${{ secrets.APPLE_API_KEY }} --apiIssuer ${{ secrets.APPLE_API_ISSUER_ID }}
+  macos:
+    runs-on: macos-latest
+    permissions:
+      contents: write
+    defaults:
+      run:
+        working-directory: ./flutter/speed
+
+    steps:
+      # Clonar o repositório principal do Flutter
+      - uses: actions/checkout@v4
+        if: ${{ inputs.macos}}
+        with:
+          repository: cloudfysystems/FLUTTER
+          ref: main
+          token: ${{ secrets.GH_TOKEN }}
+          path: flutter
+
+      # Clonar o repositório de versão
+      - uses: actions/checkout@v4
+        if: ${{ inputs.macos}}
+        with:
+          path: version-repo
+
+      # Ler e atualizar a versão
+      - name: Ler versão atual
+        if: ${{ inputs.macos}}
+        working-directory: version-repo
+        shell: bash
+        run: |
+          VERSION_FILE="versionMacos.json"
+
+          # Atualiza o JSON corretamente
+          jq '.speedy.build += 1 | .speedy.version += 1 | .speedy.patch = 0' "$VERSION_FILE" > tmp.json
+
+          mv tmp.json "$VERSION_FILE"
+
+          # Pega os valores após a atualização
+          BUILD=$(jq -r '.speedy.build' "$VERSION_FILE")
+          VERSION=$(jq -r '.speedy.version' "$VERSION_FILE")
+          SIMPLE=$(jq -r '.speedy.simple' "$VERSION_FILE")
+
+          echo "Versao Build: $BUILD"
+          echo "Versao Version: $VERSION"
+          echo "Versao Gerada: $SIMPLE.$VERSION.0"
+
+          echo "VERSAO=$SIMPLE.$VERSION.0" >> $GITHUB_ENV
+          echo "VERSAO_BUILD=$BUILD" >> $GITHUB_ENV
+
+          echo "Novo JSON:"
+          cat "$VERSION_FILE"
+
+      # Criar o arquivo env/prod.json
+      - name: Gerar env/prod.json
+        if: ${{ inputs.macos}}
+        run: |
+          mkdir -p ./env
+          echo '${{ secrets.ENV_PROD }}' > ./env/prod.json
+          cat ./env/prod.json
+
+      - name: Import code sign
+        if: ${{ inputs.macos}}
+        uses: Apple-Actions/import-codesign-certs@v1
+        with:
+          p12-file-base64: ${{ secrets.MACOS_CERT_BASE64 }}
+          p12-password: ${{ secrets.MACOS_CERT_PSW }}
+
+      - name: Configure Auth Key
+        if: ${{ inputs.macos}}
+        run: |
+          mkdir -p ~/.appstoreconnect/private_keys
+          echo "${{ secrets.APPLE_API_PRIVATE_KEY }}" > ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APPLE_API_KEY }}.p8
+          chmod 600 ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APPLE_API_KEY }}.p8
+
+      # Atualizar versão no arquivo Dart
+      - name: Atualiza versão no arquivo Dart e pubspec.yaml
+        if: ${{ inputs.macos }}
+        shell: bash
+        run: |
+          FILE="lib/Environment/Version.dart"
+          NOVA_VERSAO="${{ env.VERSAO }}"
+              
+          # Atualiza Version.dart
+          sed -i '' "s/const String Version = \".*\"/const String Version = \"$NOVA_VERSAO\"/" "$FILE"
+          cat "$FILE"
+              
+          # Atualiza pubspec.yaml
+          sed -i '' "s/^version:.*/version: $VERSAO+${{ env.VERSAO_BUILD }}/" pubspec.yaml
+          cat pubspec.yaml
+      # Setup Shorebird
+      - name: 🐦 Setup Shorebird
+        if: ${{ inputs.macos}}
+        uses: shorebirdtech/setup-shorebird@v1
+        with:
+          cache: true
+
+      # Executar build do Shorebird
+      - name: 🚀 Shorebird Release
+        if: ${{ inputs.macos}}
+        id: shorebird-release
+        uses: shorebirdtech/shorebird-release@v1
+        with:
+          args: --dart-define-from-file=env/prod.json
+          platform: macos
+          flutter-version: ${{vars.FLUTTER_VERSION_SDK_ANDROID_SMART}}
+          working-directory: ./flutter/speed
+      # Assinando a aplicaçao
+      - name: Assinando a aplicação na trairagem e zipar
+        if: ${{ inputs.macos }}
+        shell: bash
+        run: |
+          cd build/macos/Build/Products/Release
+          codesign --deep --force --verbose --sign "Developer ID Application: Jose carlos Oliveira Junior (5U63429Q34" "Cloudfy Speedy POS.app"
+          ditto -c -k --keepParent "Cloudfy Speedy POS.app" CloudfySpeedyPOS.zip
+
+      - name: Notarize
+        run: |
+          xcrun notarytool submit "build/macos/Build/Products/Release/CloudfySpeedyPOS.zip" \
+            --apiKey ${{ secrets.APPLE_API_KEY }} --apiIssuer ${{ secrets.APPLE_API_ISSUER_ID }}
+            --wait
+
+      - name: Staple
+        run: |
+          xcrun stapler staple "build/macos/Build/Products/Release/Cloudfy Speedy POS.app"
+          mv "build/macos/Build/Products/Release/Cloudfy Speedy POS.app" "build/macos/Build/Products/Release/CloudfySpeedyPOS.app"
+
+      - name: Criando o release
+        if: ${{ inputs.macos}}
+        uses: softprops/action-gh-release@v1
+        with:
+          tag_name: v${{ env.VERSAO }}_SpeedyMacOS
+          name: v${{ env.VERSAO }}_SpeedyMacOS
+          files: |
+            flutter/speed/build/macos/Build/Products/Release/CloudfySpeedyPOS.app
+          body: Release gerado automaticamente.
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+
+      - name: Chamar API de alteração de dados android
+        if: ${{ inputs.ios}}
+        run: |
+          URLIOS="https://github.com/cloudfysystems/Version/releases/download/v${{ env.VERSAO }}_SpeedyMacOS/CloudfySpeedyPOS.app"
+          echo "$URLIOS"
+          echo "Chamando API de validação..."
+
+          JSON_DATA=$(cat <<EOF
+          {
+            "JSON": true,
+            "Parameters": {
+              "Versao": "${{ env.VERSAO }}",
+              "PSW": "${{ secrets.SENHA_API_ALTERAR_URL }}",
+              "URL": "$URLIOS",
+              "NR_ID": 22
+            }
+          }
+          EOF
+          )
+
+          echo $JSON_DATA
+
+          response=$(curl -s -o response.txt -w "%{http_code}" \
+            -X POST https://api.cloudfy.net.br/H02SF0107A \
+            -H "Content-Type: application/json" \
+            -d "$JSON_DATA")
+
+          echo "Código HTTP: $response"
+          cat response.txt
+
+          if [ "$response" != "200" ]; then
+            echo "❌ Falha na chamada da API. Abortando workflow."
+            exit 1
+          fi
+
+      - name: Atualizar branch com merge (se necessário)
+        if: ${{ inputs.ios}}
+        working-directory: version-repo
+        run: |
+          git config user.name "cloudfysystems"
+          git config user.email "cloudfysystems@gmail.com"
+
+          # Garante que estamos na branch correta
+          git branch --show-current
+
+          # Tenta fazer pull e merge automático
+          git pull origin HEAD --no-rebase || true
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+
+      - name: Commit das alterações
+        uses: EndBug/add-and-commit@v9
+        if: ${{ inputs.ios}}
+        with:
+          author_name: cloudfysystems
+          author_email: cloudfysystems@gmail.com
+          message: "alterada versão do build IOS"
+          cwd: ./version-repo
+          add: "versionMacos.json"
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+
   #Job que vai atualizar o git, sincronizar os fontes
   FinishJob:
     needs:
